# Generated by Django 5.1.1 on 2025-03-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('membre', 'Membre'), ('point_focal', 'Point Focal'), ('responsable', 'Responsable'), ('cabinet', 'Cabinet MFB'), ('visiteur', 'Visiteur')], max_length=20),
        ),
    ]
