# Generated by Django 5.1.1 on 2025-02-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_comment_newscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='resume',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Résumé'),
        ),
    ]
