# Generated by Django 5.1.1 on 2025-01-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('nombre_produits', models.PositiveIntegerField(default=0)),
                ('nombre_actions', models.PositiveIntegerField(default=0)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('impact', models.TextField()),
                ('horizon', models.CharField(max_length=9)),
                ('nombre_effets', models.PositiveIntegerField(default=0)),
                ('nombre_produits', models.PositiveIntegerField(default=0)),
                ('nombre_actions', models.PositiveIntegerField(default=0)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
                ('effet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effet_action', to='planning.effet')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_action', to='planning.planaction')),
            ],
        ),
        migrations.AddField(
            model_name='effet',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_effet', to='planning.planaction'),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('nombre_actions', models.PositiveIntegerField(default=0)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
                ('effet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effet_produit', to='planning.effet')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_produit', to='planning.planaction')),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('reforme', 'Réforme'), ('investissement', 'Investissement'), ('etude', 'Étude'), ('texte', 'Texte'), ('odinaire', 'Activité ordinaire')], max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('cible', models.PositiveIntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_activite', to='planning.action')),
                ('effet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effet_activite', to='planning.effet')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_activite', to='planning.planaction')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_activite', to='planning.produit')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_action', to='planning.produit'),
        ),
    ]
