# Generated by Django 5.1.1 on 2025-03-13 08:12

import django.db.models.deletion
import planning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('couts', models.JSONField(default=planning.models.default)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('impact', models.TextField()),
                ('annee_debut', models.PositiveIntegerField(default=2025)),
                ('horizon', models.PositiveIntegerField()),
                ('couts', models.JSONField(default=planning.models.default)),
                ('nombre_effets', models.PositiveIntegerField(default=0)),
                ('nombre_produits', models.PositiveIntegerField(default=0)),
                ('nombre_actions', models.PositiveIntegerField(default=0)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Réforme', 'Réforme'), ('Investissement', 'Investissement'), ('Etude', 'Etude'), ('Texte', 'Texte'), ('Activité ordinaire', 'Activité ordinaire')], max_length=50)),
                ('indicateur_label', models.CharField(max_length=255)),
                ('indicateur_reference', models.CharField(max_length=255)),
                ('cibles', models.JSONField(default=planning.models.default)),
                ('couts', models.JSONField(default=planning.models.default)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_activite', to='planning.action')),
                ('point_focal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_focal_activites', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_activites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Effet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('couts', models.JSONField(default=planning.models.default)),
                ('nombre_produits', models.PositiveIntegerField(default=0)),
                ('nombre_actions', models.PositiveIntegerField(default=0)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_effet', to='planning.planaction')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('couts', models.JSONField(default=planning.models.default)),
                ('nombre_actions', models.PositiveIntegerField(default=0)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
                ('effet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effet_produit', to='planning.effet')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_action', to='planning.produit'),
        ),
    ]
