# Generated by Django 5.1.1 on 2025-03-10 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('couts', models.JSONField(default=list)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActiviteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifications', models.JSONField()),
                ('statut_apres', models.CharField(choices=[('Draft', 'Brouillon'), ('Submitted_SE', 'Soumise au SE'), ('Pending_SE', 'En attente SE'), ('Réalisée', 'Réalisée'), ('Non réalisée', 'Non réalisée'), ('Supprimée', 'Supprimée'), ('Reprogrammée', 'Reprogrammée'), ('Rejeté', 'Rejetée')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Effet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('couts', models.JSONField(default=list)),
                ('nombre_produits', models.PositiveIntegerField(default=0)),
                ('nombre_actions', models.PositiveIntegerField(default=0)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('impact', models.TextField()),
                ('annee_debut', models.PositiveIntegerField(default=2025)),
                ('horizon', models.PositiveIntegerField()),
                ('couts', models.JSONField(default=list)),
                ('statut_pao', models.JSONField(default=list)),
                ('nombre_effets', models.PositiveIntegerField(default=0)),
                ('nombre_produits', models.PositiveIntegerField(default=0)),
                ('nombre_actions', models.PositiveIntegerField(default=0)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('couts', models.JSONField(default=list)),
                ('nombre_actions', models.PositiveIntegerField(default=0)),
                ('nombre_activites', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Réforme', 'Réforme'), ('Investissement', 'Investissement'), ('Etude', 'Etude'), ('Texte', 'Texte'), ('Activité ordinaire', 'Activité ordinaire')], max_length=50)),
                ('indicateur_label', models.CharField(max_length=255)),
                ('indicateur_reference', models.CharField(max_length=255)),
                ('cibles', models.JSONField(default=list)),
                ('realisation', models.JSONField(default=list)),
                ('couts', models.JSONField(default=list)),
                ('etat_avancement', models.TextField(blank=True, default='')),
                ('commentaire', models.TextField(blank=True, default='')),
                ('commentaire_se', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('pending_changes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Non entamée', 'Non entamée'), ('En cours', 'En cours'), ('Réalisée', 'Réalisée'), ('Non réalisée', 'Non réalisée'), ('Supprimée', 'Supprimée'), ('Reprogrammée', 'Reprogrammée')], default='Non entamée', max_length=20)),
                ('matrix_status', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_activite', to='planning.action')),
            ],
        ),
    ]
