# Generated by Django 5.1.1 on 2025-03-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='alertes_envoyees',
            field=models.JSONField(default=dict),
        ),
    ]
