# Generated by Django 5.1.1 on 2025-02-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='cible',
        ),
        migrations.AddField(
            model_name='activite',
            name='cibles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='activite',
            name='couts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='activite',
            name='indicator',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='planaction',
            name='annee_debut',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='horizon',
            field=models.PositiveIntegerField(),
        ),
    ]
