# Generated by Django 5.1.1 on 2025-03-23 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='point_focal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_focal_activites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activite',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_activites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitelog',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='planning.activite'),
        ),
        migrations.AddField(
            model_name='activitelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='effet',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_effet', to='planning.planaction'),
        ),
        migrations.AddField(
            model_name='produit',
            name='effet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effet_produit', to='planning.effet'),
        ),
        migrations.AddField(
            model_name='action',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_action', to='planning.produit'),
        ),
    ]
