# Generated by Django 5.1.1 on 2025-03-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='status',
            field=models.CharField(choices=[('Non entamée', 'Non entamée'), ('En cours', 'En cours'), ('Réalisée', 'Réalisée'), ('Non réalisée', 'Non réalisée'), ('Supprimée', 'Supprimée'), ('Reprogrammée', 'Reprogrammée'), ('Pending_SE', 'En attente SE'), ('Submitted_SE', 'Soumise au SE')], default='Non entamée', max_length=20),
        ),
    ]
