# Generated by Django 5.1.1 on 2025-03-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_activite_alertes_envoyees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitelog',
            name='statut_apres',
            field=models.CharField(choices=[('Non évaluée', 'Non évaluée'), ('En cours', 'En cours'), ('Réalisée', 'Réalisée'), ('Non réalisée', 'Non réalisée'), ('Supprimée', 'Supprimée'), ('Reprogrammée', 'Reprogrammée')], max_length=50),
        ),
    ]
