# Generated by Django 5.1.1 on 2025-02-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_action_couts_effet_couts_planaction_couts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='nombre_activites',
        ),
        migrations.RemoveField(
            model_name='effet',
            name='nombre_actions',
        ),
        migrations.RemoveField(
            model_name='effet',
            name='nombre_activites',
        ),
        migrations.RemoveField(
            model_name='effet',
            name='nombre_produits',
        ),
        migrations.RemoveField(
            model_name='planaction',
            name='nombre_actions',
        ),
        migrations.RemoveField(
            model_name='planaction',
            name='nombre_activites',
        ),
        migrations.RemoveField(
            model_name='planaction',
            name='nombre_effets',
        ),
        migrations.RemoveField(
            model_name='planaction',
            name='nombre_produits',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nombre_actions',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nombre_activites',
        ),
    ]
