# Generated by Django 5.1.1 on 2025-03-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_activite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='commentaire',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='activite',
            name='commentaire_se',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='activite',
            name='etat_avancement',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='activite',
            name='pending_changes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='activite',
            name='status',
            field=models.JSONField(default=list),
        ),
    ]
