# Generated by Django 5.2.10 on 2026-02-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_activite_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='structure',
            field=models.CharField(blank=True, help_text="Structure responsable de l'activité", max_length=255, null=True),
        ),
    ]
