# Generated by Django 5.1.1 on 2025-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_activitelog_statut_apres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='alertes_envoyees',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
