# Generated by Django 5.1.1 on 2025-03-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_activite_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='periodes_execution',
            field=models.JSONField(default=list),
        ),
    ]
