# Generated by Django 5.1.1 on 2025-02-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_remove_action_nombre_activites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='couts',
        ),
        migrations.RemoveField(
            model_name='effet',
            name='couts',
        ),
        migrations.RemoveField(
            model_name='planaction',
            name='couts',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='couts',
        ),
        migrations.AlterField(
            model_name='activite',
            name='type',
            field=models.CharField(choices=[('reforme', 'Réforme'), ('investissement', 'Investissement'), ('etude', 'Étude'), ('texte', 'Texte'), ('odinaire', 'Activité ordinaire')], max_length=50),
        ),
    ]
