# Generated by Django 5.2.10 on 2026-02-25 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_add_structure_to_activite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='point_focal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_focal_activites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activite',
            name='structure',
            field=models.CharField(default='DGBF', help_text="Structure responsable de l'activité", max_length=255),
            preserve_default=False,
        ),
    ]
