# Generated by Django 5.1.1 on 2025-02-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_remove_action_couts_remove_effet_couts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='couts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='effet',
            name='couts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='planaction',
            name='couts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='produit',
            name='couts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='activite',
            name='type',
            field=models.CharField(choices=[('reforme', 'Réforme'), ('investissement', 'Investissement'), ('etude', 'Étude'), ('texte', 'Texte'), ('ordinaire', 'Activité ordinaire')], max_length=50),
        ),
    ]
