# Generated by Django 5.2.10 on 2026-03-06 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_activite_point_focal_alter_activite_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='structure',
        ),
    ]
