# Generated by Django 5.2.10 on 2026-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_remove_activite_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='structure',
            field=models.CharField(blank=True, choices=[('DGI', 'DGI'), ('DGD', 'DGD'), ('DGTCP', 'DGTCP'), ('DGMP', 'DGMP'), ('DGF', 'DGF'), ('DGBF', 'DGBF'), ('DGE', 'DGE')], default='', max_length=50),
        ),
    ]
