# Generated by Django 5.1.1 on 2025-02-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_action_couts_effet_couts_planaction_couts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='effet',
            name='nombre_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='effet',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='effet',
            name='nombre_produits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planaction',
            name='nombre_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planaction',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planaction',
            name='nombre_effets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planaction',
            name='nombre_produits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
