# Generated by Django 5.1.1 on 2025-02-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_action_nombre_activites_effet_nombre_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaction',
            name='couts',
            field=models.JSONField(blank='True', default=list),
        ),
    ]
