# Generated by Django 5.2.10 on 2026-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_alter_action_titre_alter_activite_indicateur_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='titre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='activite',
            name='indicateur_label',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='activite',
            name='indicateur_reference',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='activite',
            name='titre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='effet',
            name='titre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='titre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='produit',
            name='titre',
            field=models.CharField(max_length=500),
        ),
    ]
