# Generated by Django 5.1.1 on 2025-02-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_alter_planaction_couts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='couts',
            field=models.JSONField(blank='True', default=list),
        ),
        migrations.AlterField(
            model_name='action',
            name='nombre_activites',
            field=models.PositiveIntegerField(blank='True', default=0),
        ),
        migrations.AlterField(
            model_name='activite',
            name='couts',
            field=models.JSONField(blank='True', default=list),
        ),
        migrations.AlterField(
            model_name='effet',
            name='couts',
            field=models.JSONField(blank='True', default=list),
        ),
        migrations.AlterField(
            model_name='effet',
            name='nombre_actions',
            field=models.PositiveIntegerField(blank='True', default=0),
        ),
        migrations.AlterField(
            model_name='effet',
            name='nombre_activites',
            field=models.PositiveIntegerField(blank='True', default=0),
        ),
        migrations.AlterField(
            model_name='effet',
            name='nombre_produits',
            field=models.PositiveIntegerField(blank='True', default=0),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_actions',
            field=models.PositiveIntegerField(blank='True', default=0),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_activites',
            field=models.PositiveIntegerField(blank='True', default=0),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_effets',
            field=models.PositiveIntegerField(blank='True', default=0),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_produits',
            field=models.PositiveIntegerField(blank='True', default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='couts',
            field=models.JSONField(blank='True', default=list),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nombre_actions',
            field=models.PositiveIntegerField(blank='True', default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nombre_activites',
            field=models.PositiveIntegerField(blank='True', default=0),
        ),
    ]
