# Generated by Django 5.1.1 on 2025-02-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_alter_action_couts_alter_action_nombre_activites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activite',
            old_name='reference',
            new_name='indicateur_label',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='indicator',
        ),
        migrations.AddField(
            model_name='activite',
            name='indicateur_reference',
            field=models.CharField(default='True', max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='couts',
            field=models.JSONField(default=list),
        ),
    ]
