# Generated by Django 5.2.10 on 2026-08-17 23:37

import django.db.models.deletion
import planning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_alter_action_titre_alter_activite_indicateur_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='activitelog',
            options={'ordering': ['-timestamp'], 'verbose_name': "Journal d'activité", 'verbose_name_plural': "Journaux d'activités"},
        ),
        migrations.AlterModelOptions(
            name='effet',
            options={'verbose_name': 'Effet', 'verbose_name_plural': 'Effets'},
        ),
        migrations.AlterModelOptions(
            name='planaction',
            options={'verbose_name': "Plan d'actions", 'verbose_name_plural': "Plans d'actions"},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.CreateModel(
            name='PreuveRealisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('document', 'Document'), ('lien', 'Lien'), ('image', 'Image'), ('video', 'Vidéo')], max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=planning.models.preuve_directory_path)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('annee', models.PositiveIntegerField()),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='planning.activite')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preuve de réalisation',
                'verbose_name_plural': 'Preuves de réalisation',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
