# Generated by Django 5.2.10 on 2026-08-17 23:46

import django.db.models.deletion
import planning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_alter_action_options_alter_activitelog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('trimestre', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4')], max_length=2)),
                ('fichier', models.FileField(upload_to=planning.models.rapport_directory_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_emails', models.JSONField(blank=True, default=list)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='planning.planaction')),
            ],
            options={
                'verbose_name': 'Rapport trimestriel',
                'verbose_name_plural': 'Rapports trimestriels',
                'ordering': ['-generated_at'],
                'unique_together': {('plan', 'annee', 'trimestre')},
            },
        ),
    ]
