# Generated by Django 5.1.1 on 2025-02-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_rename_reference_activite_indicateur_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='indicateur_reference',
            field=models.CharField(blank='True', max_length=255),
        ),
    ]
