# Generated by Django 5.1.1 on 2025-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_alter_activite_indicateur_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='indicateur_reference',
            field=models.CharField(max_length=255),
        ),
    ]
