# Generated by Django 5.1.1 on 2025-02-19 14:02

import planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_alter_activite_indicateur_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='effet',
        ),
        migrations.RemoveField(
            model_name='action',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='effet',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='plan',
        ),
        migrations.AlterField(
            model_name='action',
            name='couts',
            field=models.JSONField(default=planning.models.default),
        ),
        migrations.AlterField(
            model_name='action',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activite',
            name='cibles',
            field=models.JSONField(default=planning.models.default),
        ),
        migrations.AlterField(
            model_name='activite',
            name='couts',
            field=models.JSONField(default=planning.models.default),
        ),
        migrations.AlterField(
            model_name='effet',
            name='couts',
            field=models.JSONField(default=planning.models.default),
        ),
        migrations.AlterField(
            model_name='effet',
            name='nombre_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='effet',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='effet',
            name='nombre_produits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='couts',
            field=models.JSONField(default=planning.models.default),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_effets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_produits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='couts',
            field=models.JSONField(default=planning.models.default),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nombre_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
