# Generated by Django 5.1.1 on 2025-02-19 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_remove_action_effet_remove_action_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='point_focal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='point_focal_activites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activite',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_activites', to=settings.AUTH_USER_MODEL),
        ),
    ]
