# Generated by Django 5.1.1 on 2025-02-07 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_alter_action_couts_alter_action_nombre_activites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='effet',
        ),
        migrations.RemoveField(
            model_name='action',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='effet',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='plan',
        ),
        migrations.AlterField(
            model_name='action',
            name='couts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='action',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='action',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_actions', to='planning.produit'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_activites', to='planning.action'),
        ),
        migrations.AlterField(
            model_name='effet',
            name='couts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='effet',
            name='nombre_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='effet',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='effet',
            name='nombre_produits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='effet',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_effets', to='planning.planaction'),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='couts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_effets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='nombre_produits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='couts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='produit',
            name='effet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effet_produits', to='planning.effet'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nombre_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nombre_activites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
