# Generated by Django 5.1.1 on 2025-02-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_activite_point_focal_activite_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='type',
            field=models.CharField(choices=[('Réforme', 'Réforme'), ('Investissement', 'Investissement'), ('Etude', 'Etude'), ('Texte', 'Texte'), ('Activité ordinaire', 'Activité ordinaire')], max_length=50),
        ),
    ]
