# Generated by Django 5.1.1 on 2025-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_remove_action_effet_remove_action_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='couts',
            field=models.JSONField(default=[0, 0, 0]),
        ),
        migrations.AlterField(
            model_name='activite',
            name='cibles',
            field=models.JSONField(default=[0, 0, 0]),
        ),
        migrations.AlterField(
            model_name='activite',
            name='couts',
            field=models.JSONField(default=[0, 0, 0]),
        ),
        migrations.AlterField(
            model_name='effet',
            name='couts',
            field=models.JSONField(default=[0, 0, 0]),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='couts',
            field=models.JSONField(default=[0, 0, 0]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='couts',
            field=models.JSONField(default=[0, 0, 0]),
        ),
    ]
