# Generated by Django 5.1.1 on 2025-02-14 09:40

import planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_alter_action_couts_alter_activite_cibles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='couts',
            field=models.JSONField(default=planning.models.default),
        ),
        migrations.AlterField(
            model_name='activite',
            name='cibles',
            field=models.JSONField(default=planning.models.default),
        ),
        migrations.AlterField(
            model_name='activite',
            name='couts',
            field=models.JSONField(default=planning.models.default),
        ),
        migrations.AlterField(
            model_name='effet',
            name='couts',
            field=models.JSONField(default=planning.models.default),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='couts',
            field=models.JSONField(default=planning.models.default),
        ),
        migrations.AlterField(
            model_name='produit',
            name='couts',
            field=models.JSONField(default=planning.models.default),
        ),
    ]
