# Generated by Django 5.1.1 on 2025-02-12 17:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.blog_directory_path, verbose_name='Image de couverture'),
        ),
    ]
