# Generated by Django 5.1.1 on 2025-02-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_comment_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='author',
            new_name='user',
        ),
    ]
