# Generated by Django 5.1.1 on 2025-03-23 02:45

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document_dpse_archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_dpse_archives)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_dpse_archives, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture')),
            ],
        ),
        migrations.CreateModel(
            name='Document_dpse_planification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_dpse_planification)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_dpse_planification, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture')),
            ],
        ),
        migrations.CreateModel(
            name='Document_dpse_qualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_dpse_qualite)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_dpse_qualite, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture')),
            ],
        ),
        migrations.CreateModel(
            name='Document_dpse_statistiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_dpse_statistiques)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_dpse_statistiques, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture')),
            ],
        ),
        migrations.CreateModel(
            name='Document_dpse_suivi_evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_dpse_suivi_evaluation)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_dpse_suivi_evaluation, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture')),
            ],
        ),
        migrations.CreateModel(
            name='Document_mfb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_mfb)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_mfb, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture')),
            ],
        ),
    ]
