# Generated by Django 5.1.1 on 2025-03-06 19:31

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_dpse_archives',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_dpse_archives, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='document_dpse_planification',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_dpse_planification, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='document_dpse_qualite',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_dpse_qualite, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='document_dpse_statistiques',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_dpse_statistiques, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='document_dpse_suivi_evaluation',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_dpse_suivi_evaluation, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='document_mfb',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.cover_directory_path_mfb, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image de couverture'),
        ),
    ]
