# Generated by Django 5.1.1 on 2025-03-23 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document_dpse_archives',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_dpse_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document_dpse_planification',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_dpse_planification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document_dpse_qualite',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_dpse_qualite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document_dpse_statistiques',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_dpse_statistiques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document_dpse_suivi_evaluation',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_dpse_suivi_evaluation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document_mfb',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_mfb', to=settings.AUTH_USER_MODEL),
        ),
    ]
