# Generated by Django 5.1.1 on 2025-02-15 18:34

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_dpse_archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_dpse_archives)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_dpse_archives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document_dpse_planification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_dpse_planification)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_dpse_planification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document_dpse_qualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_dpse_qualite)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_dpse_qualite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document_dpse_statistiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_dpse_statistiques)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_dpse_statistiques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document_dpse_suivi_evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_dpse_suivi_evaluation)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_dpse_suivi_evaluation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document_mfb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pans', models.TextField()),
                ('results', models.TextField()),
                ('file', models.FileField(upload_to=documents.models.document_directory_path_mfb)),
                ('uid', models.CharField(blank=True, editable=False, max_length=36, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_mfb', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
