# Generated by Django 5.1.1 on 2025-02-12 17:40

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.news_directory_path, verbose_name='Image associée'),
        ),
    ]
